#!/usr/bin/python
count = 0
string = "BaCoNscIphErorTHEbacOnIANCiPHeriSameThODoFsTEGaNOGrapHYaMEThoDOfHidIngAsECRetMeSsaGeasOpPOsEdTOaTRUeCiPHeRdEVIseDBYfrancisbAcoNaMessAgeIscoNCeALEDinTHepRESenTatIoNOFTexTratHerthaNiTscoNteNttOenCODeAMEsSaGeeaChlETterOfTHepLAInTextIsrePLAcEDByAgroUpoFfIvEOFtheLEttERSaorBThISrEplACEmentisDoneaccoRDinGtothEalphABeTOFtHeBACOnIANcIpHeRsHoWnbElOwNoTe:ASeCoNdvErSiOnoFBaCoNSCiPhEruSeSAUnIqUecOdEFoREaChlEtTeRiNOtHeRWoRdSiaNdjeAcHHaSItSOwNPaTtErNtHewRiTeRMuStmAkEUsEOftWodIfFeReNttYpEfAcEsfOrtHiSCiPhErAfTeRPrEpArInGAFaLsEMeSsAgEWiThtHesAmENuMbEroFLeTtErSAsaLloFThEAsaNdbSIntHerEaLsEcReTMeSsAgEtWotYpEfAcEsaRecHoSeNoNetORePrEsEnTAsaNdtHeoThErbStHeNEaChlEtTeROftHefAlSemEsSaGemUsTBepReSeNtEdiNThEApPrOpRiAtETyPeFaCeAcCoRdInGTowHeThEriTStAnDsfOraNAOrabTodEcOdEThEMeSsAgEtHerEvErSemEtHoDIsaPpLiEdEaChTyPeFaCe1LeTtEriNThEFaLsEMeSsAgEIsrEpLaCeDWiThaNAAnDEaChTyPeFaCe2LeTtEriSRePlAcEdwItHABtHebAcOnIaNAlPhAbEtiSThEnuSeDTorEcOvErtHeoRiGiNaLMeSsAgEaNymEtHoDOfwRiTiNgtHemEsSaGetHaTAlLoWstWodIsTiNcTRePrEsEnTaTiOnSFoREaChcHaRaCtErcAnbEUsEdfOrtHebAcOncIpHeRbAcOnhImSeLfpRePaReDABiLiTeRaLAlPhAbEtFoRHaNdWrItTeNCaPiTaLAnDSmAlLLeTtErSWiTheAcHHaViNgtWoaLtErNaTiVefOrMsOnETobEUsEdaSAAnDThEOtHeRAsbThIswAspUbLiShEdaSAniLlUsTrAtEdpLaTeiNHiSDeaUgMeNtIssCiEnTiArUmThEAdVaNcEmEnTOflEaRnInGBeCaUsEAnYMeSsAgEOftHerIgHtlEnGtHCaNBeuSeDTocArRytHeeNcOdInGtHesEcReTMeSsAgEIseFfEcTiVeLyhIdDeNInpLaInsIgHtThEFaLsEMeSsAgECaNBeoNAnYToPiCAnDThUscAndIsTrAcTAPeRsOnsEeKiNgtOFiNdtHerEaLMeSsAgE"
strlen = (len(string)/5)
z=0;
for y in range(strlen):

    for x in range(5):
        if string[x+z].isupper():
            count = count + (2 ** (4-(x%5)))
    print(chr(count+97))
    count=0
    z=z+5
