#!/bin/bash
function randomize(){
for (( i=1; i<=$1; i++ ))
do
sorted=$(echo $2 | sed -e $'s/,/\\n/g' | sort -R);
#awk -F'\n' -v OFS=", " '$1=$1' <<< $sorted;
sorted=$(echo $sorted | sed -e 's/\ /\,\ /g');
echo $sorted;
done;
}
function select_randomizer(){
	if [ $1 == 's' ];
	then
	randomize $2 $3;
	elif [ $1 == '-h' ] || [ $1 == '' ];
	then
	echo "usage: randomize_answers [single_string|s]|[all_answers|a] [{number_of_answers}2|4|5] {string,of,answers}"
	else
	randomize_all $2 $3;
	fi
}

select_randomizer $1 $2 $3;
#echo sorted;
