#!/bin/dash
find -iname *.zip > tmp;

#find -iname *.nds >> tmp
sed -i "s/\.\///" tmp;
FILENAME=tmp;
while read line
do
    echo "$line";
    advzip -4 -z "$line";
    wine deflopt.exe "$line";
    ./defluff <"$line" > "$line-1";
    mv "$line-1" "$line";
done < tmp
